# Generated by Django 4.1.1 on 2023-12-04 05:21

import coderedcms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_dailyquotespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquotespage',
            name='poetry',
            field=coderedcms.fields.CoderedStreamField(blank=True, use_json_field=True, verbose_name='Poetry'),
        ),
    ]
