# Generated by Django 4.1.1 on 2023-12-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_dailyquotespage_poetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquotespage',
            name='poetry_layout',
            field=models.CharField(choices=[('one_column', 'One Column'), ('two_columns', 'Two Columns')], default='one_column', max_length=20, verbose_name='Poetry Layout'),
        ),
    ]
