# Generated by Django 4.1.1 on 2023-12-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_dailyquotespage_poetry_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquotespage',
            name='poetry_layout',
        ),
    ]
