# Generated by Django 4.2.8 on 2023-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_dailyquotespage_poetry_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaymessagepage',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
