# Generated by Django 4.2.8 on 2023-12-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_todaymessagepage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaymessagepage',
            name='name',
        ),
        migrations.AddField(
            model_name='todaymessagepage',
            name='display_title',
            field=models.CharField(default=0, max_length=255, verbose_name='Display title'),
            preserve_default=False,
        ),
    ]
