# Generated by Django 4.2.8 on 2023-12-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_dailyquotespage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquotespage',
            name='poetry',
        ),
    ]
