# Generated by Django 4.1.1 on 2023-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDaysInLunarCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunar_date', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Important Days in Lunar Calendar',
                'verbose_name_plural': 'Important Days in Lunar Calendar',
            },
        ),
    ]
