# Generated by Django 4.1.1 on 2023-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_importantdaysinlunarcalendar_lunar_date_in_adhikamasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='lunar date'),
        ),
    ]
