# Generated by Django 4.1.1 on 2023-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_remove_importantdaysinsolarcalendar_solar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantdaysinsolarcalendar',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='month'),
        ),
    ]
