# Generated by Django 4.1.1 on 2023-12-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
        ('utils', '0008_alter_importantdaysinlunarcalendar_lunar_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='webpage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_day_lunar', to='website.webpage', verbose_name='Web Page'),
        ),
        migrations.AddField(
            model_name='importantdaysinsolarcalendar',
            name='webpage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_day_solar', to='website.webpage', verbose_name='Web Page'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='details',
            field=models.CharField(max_length=255, verbose_name='details'),
        ),
    ]
