# Generated by Django 4.1.1 on 2023-12-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_data'),
        ('utils', '0010_alter_importantdaysinsolarcalendar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantdaysinlunarcalendar',
            name='webpage',
        ),
        migrations.RemoveField(
            model_name='importantdaysinsolarcalendar',
            name='webpage',
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='article_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_day_lunar', to='website.articlepage', verbose_name='Article Page'),
        ),
        migrations.AddField(
            model_name='importantdaysinsolarcalendar',
            name='article_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_day_solar', to='website.articlepage', verbose_name='Article Page'),
        ),
    ]
