# Generated by Django 4.1.1 on 2023-12-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('utils', '0011_remove_importantdaysinlunarcalendar_webpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantdaysinlunarcalendar',
            options={'ordering': ['month_lunar', 'day_lunar'], 'verbose_name': 'Important Days in Lunar Calendar', 'verbose_name_plural': 'Important Days in Lunar Calendar'},
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='day_adhikamasa',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default=0, max_length=2, verbose_name='day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='day_lunar',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default=0, max_length=2, verbose_name='day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='month_adhikamasa',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('88', '88'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=0, max_length=2, verbose_name='month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='month_lunar',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('88', '88'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=0, max_length=2, verbose_name='month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='moon_phase_adhikamasa',
            field=models.CharField(choices=[('waxing', 'ขึ้น'), ('waning', 'แรม')], default='waxing', max_length=10, verbose_name='moon phase'),
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='moon_phase_lunar',
            field=models.CharField(choices=[('waxing', 'ขึ้น'), ('waning', 'แรม')], default='waxing', max_length=10, verbose_name='moon phase'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='article_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_day_lunar', to='wagtailcore.page', verbose_name='Article Page'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date',
            field=models.CharField(blank=True, default=0, max_length=25, verbose_name='lunar date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date_in_adhikamasa',
            field=models.CharField(blank=True, default=0, max_length=25, verbose_name='lunar date in adhikamasa'),
            preserve_default=False,
        ),
    ]
