# Generated by Django 4.1.1 on 2023-12-02 12:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_remove_importantdaysinlunarcalendar_article_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunarcalendardetail',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='lunarcalendardetail',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lunarcalendardetail',
            name='lunar_calendar_day',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunar_calendar_details', to='utils.importantdaysinlunarcalendar', verbose_name='Detail'),
        ),
    ]
