# Generated by Django 4.1.1 on 2023-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_alter_lunarcalendardetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunarcalendardetail',
            name='detail_text',
        ),
        migrations.AddField(
            model_name='lunarcalendardetail',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
