# Generated by Django 4.1.1 on 2023-12-03 00:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('utils', '0016_alter_importantdaysinlunarcalendar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantdaysinsolarcalendar',
            name='article_page',
        ),
        migrations.RemoveField(
            model_name='importantdaysinsolarcalendar',
            name='details',
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lc_day',
            field=models.CharField(choices=[('01', ' 1'), ('02', ' 2'), ('03', ' 3'), ('04', ' 4'), ('05', ' 5'), ('06', ' 6'), ('07', ' 7'), ('08', ' 8'), ('09', ' 9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lc_day_adhikamasa',
            field=models.CharField(choices=[('01', ' 1'), ('02', ' 2'), ('03', ' 3'), ('04', ' 4'), ('05', ' 5'), ('06', ' 6'), ('07', ' 7'), ('08', ' 8'), ('09', ' 9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lc_month',
            field=models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '88'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], max_length=2, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='lc_month_adhikamasa',
            field=models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '88'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], max_length=2, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='moon_phase',
            field=models.CharField(choices=[('01', 'ขึ้น'), ('02', 'แรม')], default='waxing', max_length=10, verbose_name='moon phase'),
        ),
        migrations.AlterField(
            model_name='importantdaysinlunarcalendar',
            name='moon_phase_adhikamasa',
            field=models.CharField(choices=[('01', 'ขึ้น'), ('02', 'แรม')], default='waxing', max_length=10, verbose_name='moon phase'),
        ),
        migrations.CreateModel(
            name='SolarCalendarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('article_page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page', verbose_name='Article Page')),
                ('solar_calendar_day', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_calendar_details', to='utils.importantdaysinsolarcalendar', verbose_name='Detail')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
