# Generated by Django 4.1.1 on 2023-12-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_moonphasecreatorform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moonphasecreatorform',
            options={},
        ),
    ]
