# Generated by Django 4.1.1 on 2023-12-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_alter_moonphasecreatorform_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoonPhaseCreatorForm',
        ),
    ]
