# Generated by Django 4.1.1 on 2023-12-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_moonphasecreatorform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoonPhaseCreatorForm',
        ),
    ]
