# Generated by Django 4.2.8 on 2023-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_moonphasecreatorform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moonphasecreatorform',
            options={'verbose_name': 'Moon Phase Creator Form', 'verbose_name_plural': 'Moon Phase Creator Form'},
        ),
        migrations.RemoveField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date',
        ),
        migrations.RemoveField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date_in_adhikamasa',
        ),
        migrations.AddField(
            model_name='lunarcalendardetail',
            name='buddhist_commemorative_day',
            field=models.BooleanField(default=True, verbose_name='Buddhist Commemorative Day'),
        ),
        migrations.AlterField(
            model_name='moonphasecreatorform',
            name='after_selected_date',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='moonphasecreatorform',
            name='before_selected_date',
            field=models.IntegerField(default=10),
        ),
    ]
