# Generated by Django 4.2.8 on 2023-12-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0024_alter_moonphasecreatorform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date',
            field=models.CharField(blank=True, max_length=25, verbose_name='lunar date'),
        ),
        migrations.AddField(
            model_name='importantdaysinlunarcalendar',
            name='lunar_date_in_adhikamasa',
            field=models.CharField(blank=True, max_length=25, verbose_name='lunar date in adhikamasa'),
        ),
    ]
