# Generated by Django 4.2.8 on 2023-12-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_patidinapakkhaganana_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patidinapakkhaganana',
            old_name='name',
            new_name='title',
        ),
    ]
