# Generated by Django 4.2.8 on 2024-01-28 14:42

import coderedcms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0029_alter_patidinapakkhaganana_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanDhammBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', coderedcms.fields.CoderedStreamField(blank=True, use_json_field=True, verbose_name='content')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PanDhamm Book',
                'verbose_name_plural': 'PanDhamm Book',
            },
        ),
    ]
