# Generated by Django 4.2.8 on 2024-01-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_pandhammbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandhammbook',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='pandhamm_book_covers/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='pandhammbook',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Short Description'),
        ),
    ]
