# Generated by Django 4.2.8 on 2024-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0033_pandhammtargetgroup_supportpublication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandhammtargetgroup',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'PanDhamm Target Group', 'verbose_name_plural': 'PanDhamm Target Groups'},
        ),
        migrations.AlterModelOptions(
            name='supportpublication',
            options={'verbose_name': 'PanDhamm Support Publication', 'verbose_name_plural': 'PanDhamm Support Publications'},
        ),
        migrations.AddField(
            model_name='pandhammtargetgroup',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
