# Generated by Django 4.2.8 on 2024-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0034_alter_pandhammtargetgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportpublication',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
    ]
