# Generated by Django 4.2.8 on 2024-01-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0035_supportpublication_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportpublication',
            name='target_group',
        ),
        migrations.AddField(
            model_name='supportpublication',
            name='target_groups',
            field=models.ManyToManyField(blank=True, to='utils.pandhammtargetgroup', verbose_name='Target Groups'),
        ),
    ]
