# Generated by Django 4.2.8 on 2024-01-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0036_remove_supportpublication_target_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandhammtarget',
            options={'verbose_name': 'Target', 'verbose_name_plural': 'Targets'},
        ),
        migrations.AlterModelOptions(
            name='pandhammtargetgroup',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Target Group', 'verbose_name_plural': 'Target Groups'},
        ),
        migrations.AddField(
            model_name='supportpublication',
            name='target_address',
            field=models.TextField(blank=True, verbose_name='Target Address'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Shipping Address'),
        ),
    ]
