# Generated by Django 4.2.8 on 2024-01-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0037_alter_pandhammtarget_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pandhammbook',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='supportpublication',
            options={'verbose_name': 'Support Publication', 'verbose_name_plural': 'Support Publications'},
        ),
    ]
