# Generated by Django 4.2.8 on 2024-01-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0038_alter_pandhammbook_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandhammtarget',
            name='group',
        ),
        migrations.RemoveField(
            model_name='supportpublication',
            name='book',
        ),
        migrations.RemoveField(
            model_name='supportpublication',
            name='target_groups',
        ),
        migrations.DeleteModel(
            name='PanDhammBook',
        ),
        migrations.DeleteModel(
            name='PanDhammTarget',
        ),
        migrations.DeleteModel(
            name='PanDhammTargetGroup',
        ),
        migrations.DeleteModel(
            name='SupportPublication',
        ),
    ]
