# Generated by Django 4.2.8 on 2024-01-31 06:28

import coderedcms.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanDhamBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short Description')),
                ('description', coderedcms.fields.CoderedStreamField(blank=True, use_json_field=True, verbose_name='content')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('initial_stock', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('cover_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_cover', to='custom_media.customimage')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='PanDhamTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Target Group',
                'verbose_name_plural': 'Target Groups',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_contribute', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('amount_contributed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('distribution_preference', models.CharField(choices=[('request_book', 'Request Book'), ('no_book_request', 'No Book Requested')], max_length=100, verbose_name='Distribution Preference')),
                ('requested_books', models.PositiveIntegerField(default=0, verbose_name='Requested Books')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP Number')),
                ('pandhann_books', models.PositiveIntegerField(default=0, verbose_name='PanDham Books')),
                ('target_address', models.TextField(blank=True, verbose_name='Target Address')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_publication', to='pandham.pandhambook', verbose_name='PanDham Book')),
                ('target_groups', models.ManyToManyField(blank=True, to='pandham.pandhamtargetgroup', verbose_name='Target Groups')),
            ],
            options={
                'verbose_name': 'Support Publication',
                'verbose_name_plural': 'Support Publications',
            },
        ),
        migrations.CreateModel(
            name='PanDhamTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('requested_books', models.PositiveIntegerField(verbose_name='Requested Books')),
                ('request_date', models.DateTimeField(verbose_name='Request Date')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Information')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pandham.pandhamtargetgroup', verbose_name='Target Group')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
            },
        ),
    ]
