# Generated by Django 4.2.8 on 2024-02-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportpublication',
            name='pandhann_books',
        ),
        migrations.AddField(
            model_name='supportpublication',
            name='for_PanDham',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of books for PanDham'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='amount_contributed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intention to support the printing and distribution.', max_digits=10, verbose_name='Contribute funds'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='book',
            field=models.ForeignKey(help_text='Select the PanDham book for support in printing and distribution.', on_delete=django.db.models.deletion.CASCADE, related_name='support_publication', to='pandham.pandhambook', verbose_name='PanDham Book'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='distribution_preference',
            field=models.CharField(choices=[('request_book', 'Request Book'), ('no_book_request', 'No Book Requested')], default='no_book_request', max_length=100, verbose_name='Distribution Preference'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='name',
            field=models.CharField(help_text='Please specify name, pseudonym, or dedication.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='note',
            field=models.TextField(blank=True, help_text='Enter any additional notes or comments.', null=True, verbose_name='Memo or Note'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='otp',
            field=models.CharField(blank=True, help_text='Enter the OTP number.', max_length=6, null=True, verbose_name='OTP'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='phone_number',
            field=models.CharField(help_text='Mobile phone number for contact and identity verification.', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Calculated result in the number of book volumes.', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='requested_books',
            field=models.PositiveIntegerField(default=1, help_text='Enter the number of books requested.', verbose_name='Requested Books'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='target_address',
            field=models.TextField(blank=True, help_text='Please provide the address of the PanDham recipient.', null=True, verbose_name='Target Address'),
        ),
        migrations.AlterField(
            model_name='supportpublication',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='Select the target groups for this support publication.', null=True, to='pandham.pandhamtargetgroup', verbose_name='Target Groups'),
        ),
    ]
