# Generated by Django 4.2.8 on 2024-02-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0002_remove_supportpublication_pandhann_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpublication',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='Select the target groups for this support publication.', to='pandham.pandhamtargetgroup', verbose_name='Target Groups'),
        ),
    ]
