# Generated by Django 4.2.8 on 2024-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0005_alter_supportpublication_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpublication',
            name='otp',
            field=models.CharField(help_text='Enter the OTP number.', max_length=6, null=True, verbose_name='OTP'),
        ),
    ]
