# Generated by Django 4.2.8 on 2024-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0006_alter_supportpublication_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpublication',
            name='otp',
            field=models.CharField(blank=True, help_text='Enter the OTP number.', max_length=6, null=True, verbose_name='OTP'),
        ),
    ]
