# Generated by Django 4.2.8 on 2024-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandham', '0009_alter_supportpublication_target_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpublication',
            name='otp',
            field=models.CharField(help_text='Enter the OTP number.', max_length=6, verbose_name='OTP'),
        ),
    ]
